name: GATE Standard Module CI (Pull Request)

on:
  workflow_call:
    inputs:
      java_version:
        description: "Version of Java on which the workflow will run"
        default: "8"
        required: false
        type: string
      java_distribution:
        description: "Java distribution to use"
        default: "zulu"
        required: false
        type: string
      test_report:
        description: "Should we publish the test report as a workflow check?"
        default: true
        required: false
        type: boolean
      maven_version:
        description: "Version of Maven to use for the build"
        default: "3.8.8"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Update submodules if necessary
        run: |
          if [ -f '.gitmodules' ]; then
            git submodule update --init --recursive --depth=1
          else
            echo "Repository does not have submodules - nothing to do"
          fi

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: ${{ inputs.maven_version }}

      # Override http://repo.gate.ac.uk to use https:// instead
      - name: Configure Maven settings
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          mirrors: >
            [
              {
                "id": "gate.ac.uk-https",
                "name": "GATE repo (secure)",
                "mirrorOf": "gate.ac.uk",
                "url": "https://repo.gate.ac.uk/content/groups/public/"
              }
            ]
          repositories: >
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          plugin_repositories: > 
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]

      - name: Build with Maven
        run: mvn --batch-mode -e clean install 

      - name: Upload Test Results
        if: inputs.test_report && (success() || failure())
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: |
            target/surefire-reports/*.xml
          
      - name: Build site
        run: mvn --batch-mode -e -DskipTests site

      # We want to avoid cacheing -SNAPSHOT dependencies from our local maven
      # cache, to ensure that we always go out and check for them again at the
      # next build in case they have changed.
      - name: Delete snapshots from m2 repository
        if: always()
        run: |
          find ~/.m2/repository -name \*-SNAPSHOT -type d -exec rm -rf {} \+ || :

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    if: inputs.test_report
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}
