name: GATE Standard Module CI (Pull Request)

on:
  workflow_call:
    inputs:
      java_version:
        description: "Version of Java on which the workflow will run"
        default: "8"
        required: false
        type: string
      java_distribution:
        description: "Java distribution to use"
        default: "zulu"
        required: false
        type: string
      test_report:
        description: "Should we publish the test report as a workflow check?"
        default: true
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
          cache: maven

      # Override http://repo.gate.ac.uk to use https:// instead
      - name: Configure Maven settings
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          mirrors: >
            [
              {
                "id": "gate.ac.uk-https",
                "name": "GATE repo (secure)",
                "mirrorOf": "gate.ac.uk",
                "url": "https://repo.gate.ac.uk/content/groups/public/"
              }
            ]
          repositories: >
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          plugin_repositories: > 
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]

      - name: Build with Maven
        run: mvn --batch-mode -e clean install 

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: inputs.test_report && (success() || failure())
        with:
          fail_if_no_tests: false
          
      - name: Build site
        run: mvn --batch-mode -e -DskipTests site

      # We want to avoid cacheing -SNAPSHOT dependencies from our local maven
      # cache, to ensure that we always go out and check for them again at the
      # next build in case they have changed.
      - name: Delete snapshots from m2 repository
        if: always()
        run: |
          find ~/.m2/repository -name \*-SNAPSHOT -type d -exec rm -rf {} \+ || :
