name: GATE Standard Module CI

on:
  workflow_call:
    inputs:
      java_version:
        description: "Version of Java on which the workflow will run"
        default: "8"
        required: false
        type: string
      java_distribution:
        description: "Java distribution to use"
        default: "zulu"
        required: false
        type: string
      test_report:
        description: "Should we publish the test report as a workflow check?"
        default: true
        required: false
        type: boolean
      default_branch:
        description: "Full refs/heads/XXX of the default branch of the calling repository, if not master"
        default: "refs/heads/master"
        required: false
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
          cache: maven

      # Override http://repo.gate.ac.uk to use https:// instead
      - uses: whelk-io/maven-settings-xml-action@v20
        with:
          mirrors: >
            [
              {
                "id": "gate.ac.uk-https",
                "name": "GATE repo (secure)",
                "mirrorOf": "gate.ac.uk",
                "url": "https://repo.gate.ac.uk/content/groups/public/"
              }
            ]
          repositories: >
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          plugin_repositories: > 
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          servers: >
            [
              {
                "id": "gate.snapshots",
                "username": "${{ secrets.GATE_REPO_USERNAME }}",
                "password": "${{ secrets.GATE_REPO_PASSWORD }}"
              }
            ]

      - name: Build with Maven
        run: mvn --batch-mode -e clean install 

      - name: Publish Test Report
        if: inputs.test_report
        uses: scacap/action-surefire-report@v1
        with:
          fail_if_no_tests: false
          
      - name: Build site
        run: mvn --batch-mode -e -DskipTests site

      - name: Upload artifact
        if: github.ref == inputs.default_branch
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'target/site'

      - name: Deploy to repo.gate.ac.uk
        if: github.ref == inputs.default_branch
        run: mvn -e -Dmaven.test.skip=true source:jar javadoc:jar deploy

  publish-site:
    if: github.ref == inputs.default_branch
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
